export const movies = [
    {
      id: 1,
      title: "Dunes",
      rate: 4,
      img: "https://i.egycdn.com/pic/WmFwZndlY21tbW12Y3Zjdk5tbWJFY3htbWFtbWFtVG1teg.jpg",
      Description: "Action,Adventure",
      video:"",
    },
    {
      id: 2,
      title: "Camp X-Ray",
      rate: 3,
      img: "https://i.egycdn.com/pic/WmFwZndlY21ibVl2dmNtRUVjY2tORXdUandUb3c.jpg",
      Description: "Action,Drama",
      video:"https://youtu.be/_1MDrwqjeGo+",
    },
    {
      id: 3,
      title: "No Time To Die",
      rate: 5,
      img: "https://i.egycdn.com/pic/WmFwZndlY21tbUVtVFlwcG1FY21FbG1ibW1tamFtdng.jpg",
      Description: "Action",
      video:"https://youtu.be/BIhNsAtPbPI",
    },
    {
      id: 4,
      title: "Fast And Furious 9",
      rate: 5,
      img: "https://i.egycdn.com/pic/WmFwZndlY21MdE5ibUV2TmJFY21qdk5qUHZOdndUZw.jpg",
      Description: "Action,Thriller",
      video:"https://www.youtube.com/embed/FUK2kdPsBws",
    },
    {
        id: 5,
        title: "The Place Beyond The Pines",
        rate: 4,
        img: "https://i.egycdn.com/pic/WmFwZndlY21ibVlibW1tYWNtcG1tWW12Y212dnR3.jpg",
        Description: "Action,Thriller",
        video:"https://youtu.be/KepnbJT5nBw",
      },
      {
        id: 6,
        title: "Venom ",
        rate: 3,
        img: "https://i.egycdn.com/pic/WmFwZndlY21UbXZjdnRjdmNtYWNjd2FtVFlibWptYm1F.jpg",
        Description: "Action,Science Fiction",
        video:"https://youtu.be/u9Mv98Gr5pY",
      },
  ];